import { NutrifitArticle, CategoryInfo } from './types';

export const categories: CategoryInfo[] = [
  {
    id: 'ciclo-hormonal',
    name: 'Ciclo Hormonal',
    description: 'Entenda as fases do ciclo menstrual e suas implicações',
    emoji: '🌸',
    color: '#e91e63',
  },
  {
    id: 'hormonios',
    name: 'Hormônios Femininos',
    description: 'Estrogênio, progesterona, testosterona e cortisol',
    emoji: '💎',
    color: '#9c27b0',
  },
  {
    id: 'condicoes-saude',
    name: 'Condições de Saúde',
    description: 'SOP, endometriose, tireoide e outras condições',
    emoji: '🏥',
    color: '#673ab7',
  },
  {
    id: 'nutricao',
    name: 'Nutrição Feminina',
    description: 'Alimentação estratégica para cada fase hormonal',
    emoji: '🥗',
    color: '#00bcd4',
  },
  {
    id: 'treinamento',
    name: 'Treinamento',
    description: 'Periodização e otimização do treino feminino',
    emoji: '💪',
    color: '#ff5722',
  },
  {
    id: 'saude-mental',
    name: 'Saúde Mental',
    description: 'Ansiedade, depressão e bem-estar emocional',
    emoji: '🧘',
    color: '#4caf50',
  },
  {
    id: 'reproducao',
    name: 'Reprodução & Fertilidade',
    description: 'Gravidez, amamentação e fertilidade',
    emoji: '🤰',
    color: '#ff9800',
  },
];

export const articles: NutrifitArticle[] = [
  {
    id: '01',
    slug: 'fisiologia-ciclo-menstrual',
    title: 'Fisiologia do Ciclo Menstrual: FSH, LH, Estrogênio e Progesterona',
    description: 'Entenda a orquestra hormonal que rege a saúde feminina e descubra como otimizar nutrição, treino e bem-estar em cada fase do ciclo',
    category: 'ciclo-hormonal',
    tags: ['FSH', 'LH', 'estrogênio', 'progesterona', 'fisiologia'],
    readTime: 25,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_01_fisiologia_ciclo_menstrual.html',
    emoji: '🌸',
    featured: true,
  },
  {
    id: '02',
    slug: 'fases-ciclo-nutricao-treino',
    title: 'Fases do Ciclo Menstrual: Nutrição e Treino Personalizados',
    description: 'Aprenda a adaptar sua alimentação e treinamento de acordo com cada fase hormonal',
    category: 'ciclo-hormonal',
    tags: ['periodização', 'nutrição cíclica', 'treino feminino'],
    readTime: 20,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_02_fases_ciclo_nutricao_treino.html',
    emoji: '🔄',
    featured: true,
  },
  {
    id: '03',
    slug: 'pms-pmdd-tratamento',
    title: 'PMS e PMDD: Sintomas e Tratamento',
    description: 'Compreenda a tensão pré-menstrual e o transtorno disfórico',
    category: 'ciclo-hormonal',
    tags: ['PMS', 'PMDD', 'sintomas pré-menstruais'],
    readTime: 18,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_03_pms_pmdd_tratamento.html',
    emoji: '😓',
  },
  {
    id: '04',
    slug: 'sop-sindrome-ovarios-policisticos',
    title: 'Síndrome dos Ovários Policísticos (SOP)',
    description: 'Tudo sobre SOP: diagnóstico, tratamento nutricional e estilo de vida',
    category: 'condicoes-saude',
    tags: ['SOP', 'PCOS', 'resistência insulina', 'hiperandrogenismo'],
    readTime: 30,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_04_sop_sindrome_ovarios_policisticos.html',
    emoji: '🏥',
    featured: true,
  },
  {
    id: '05',
    slug: 'fertilidade-nutricao-preconcepcao',
    title: 'Fertilidade e Nutrição na Pré-Concepção',
    description: 'Prepare seu corpo para uma gravidez saudável com nutrição adequada',
    category: 'reproducao',
    tags: ['fertilidade', 'pré-concepção', 'planejamento familiar'],
    readTime: 22,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_05_fertilidade_nutricao_preconcepcao.html',
    emoji: '🤰',
  },
  {
    id: '06',
    slug: 'nutricao-gravidez-completo',
    title: 'Nutrição na Gravidez: Guia Completo',
    description: 'Tudo sobre alimentação gestacional do primeiro ao terceiro trimestre',
    category: 'reproducao',
    tags: ['gravidez', 'gestação', 'nutrição gestacional'],
    readTime: 35,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_06_nutricao_gravidez_completo.html',
    emoji: '🤱',
    featured: true,
  },
  {
    id: '07',
    slug: 'celulite-tratamentos-esteticos',
    title: 'Celulite: Causas e Tratamentos Estéticos',
    description: 'Entenda a fisiologia da celulite e abordagens eficazes',
    category: 'condicoes-saude',
    tags: ['celulite', 'estética', 'gordura localizada'],
    readTime: 15,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_07_celulite_tratamentos_esteticos.html',
    emoji: '✨',
  },
  {
    id: '08',
    slug: 'colageno-nutricao-pele',
    title: 'Colágeno e Nutrição para a Pele',
    description: 'Como manter a pele saudável através da nutrição',
    category: 'nutricao',
    tags: ['colágeno', 'pele', 'antioxidantes'],
    readTime: 18,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_08_colageno_nutricao_pele.html',
    emoji: '💆',
  },
  {
    id: '09',
    slug: 'menopausa-climaterio',
    title: 'Menopausa e Climatério: Transição Hormonal',
    description: 'Navegue pela menopausa com saúde e qualidade de vida',
    category: 'hormonios',
    tags: ['menopausa', 'climatério', 'transição hormonal'],
    readTime: 28,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_09_menopausa_climaterio.html',
    emoji: '🌅',
    featured: true,
  },
  {
    id: '10',
    slug: 'treino-feminino-periodizacao',
    title: 'Treinamento Feminino: Periodização Baseada no Ciclo',
    description: 'Otimize seus resultados sincronizando treino com seu ciclo hormonal',
    category: 'treinamento',
    tags: ['periodização', 'treino feminino', 'performance'],
    readTime: 24,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_10_treino_feminino_periodizacao.html',
    emoji: '🏋️',
    featured: true,
  },
  {
    id: '11',
    slug: 'amenorreia-triade-atleta',
    title: 'Amenorreia e Tríade da Atleta Feminina',
    description: 'Reconheça e previna a tríade: baixa energia, amenorreia e osteoporose',
    category: 'treinamento',
    tags: ['amenorreia', 'tríade atleta', 'saúde óssea'],
    readTime: 26,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_11_amenorreia_triade_atleta.html',
    emoji: '⚠️',
  },
  {
    id: '12',
    slug: 'tireoide-metabolismo-feminino',
    title: 'Tireoide e Metabolismo Feminino',
    description: 'Como a tireoide afeta peso, energia e bem-estar',
    category: 'condicoes-saude',
    tags: ['tireoide', 'hipotireoidismo', 'hipertireoidismo', 'metabolismo'],
    readTime: 22,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_12_tireoide_metabolismo_feminino.html',
    emoji: '🦋',
  },
  {
    id: '13',
    slug: 'endometriose-nutricao-manejo',
    title: 'Endometriose: Nutrição e Manejo',
    description: 'Estratégias nutricionais para reduzir dor e inflamação',
    category: 'condicoes-saude',
    tags: ['endometriose', 'dor pélvica', 'anti-inflamatório'],
    readTime: 24,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_13_endometriose_nutricao_manejo.html',
    emoji: '🌺',
  },
  {
    id: '14',
    slug: 'saude-mamas-prevencao',
    title: 'Saúde das Mamas e Prevenção',
    description: 'Autocuidado e prevenção do câncer de mama',
    category: 'condicoes-saude',
    tags: ['saúde mama', 'prevenção câncer', 'autoexame'],
    readTime: 20,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_14_saude_mamas_prevencao.html',
    emoji: '🎀',
  },
  {
    id: '15',
    slug: 'infeccoes-urinarias-saude-intima',
    title: 'Infecções Urinárias e Saúde Íntima',
    description: 'Prevenção e tratamento de ITUs recorrentes',
    category: 'condicoes-saude',
    tags: ['ITU', 'cistite', 'saúde íntima'],
    readTime: 16,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_15_infeccoes_urinarias_saude_intima.html',
    emoji: '💧',
  },
  {
    id: '16',
    slug: 'libido-feminina-saude-sexual',
    title: 'Libido Feminina e Saúde Sexual',
    description: 'Fatores hormonais, nutricionais e psicológicos da libido',
    category: 'hormonios',
    tags: ['libido', 'desejo sexual', 'testosterona'],
    readTime: 20,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_16_libido_feminina_saude_sexual.html',
    emoji: '❤️',
  },
  {
    id: '17',
    slug: 'estresse-cortisol-saude-hormonal',
    title: 'Estresse, Cortisol e Saúde Hormonal',
    description: 'Como o estresse crônico desregula seus hormônios',
    category: 'hormonios',
    tags: ['cortisol', 'estresse', 'eixo HPA'],
    readTime: 22,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_17_estresse_cortisol_saude_hormonal.html',
    emoji: '😰',
  },
  {
    id: '18',
    slug: 'resistencia-insulina-mulher',
    title: 'Resistência à Insulina na Mulher',
    description: 'Identificação, prevenção e reversão da resistência insulínica',
    category: 'condicoes-saude',
    tags: ['resistência insulina', 'síndrome metabólica', 'diabetes'],
    readTime: 26,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_18_resistencia_insulina_mulher.html',
    emoji: '🩺',
  },
  {
    id: '19',
    slug: 'retencao-hidrica-inchaco',
    title: 'Retenção Hídrica e Inchaço',
    description: 'Causas hormonais e estratégias para reduzir o inchaço',
    category: 'ciclo-hormonal',
    tags: ['retenção hídrica', 'inchaço', 'edema'],
    readTime: 15,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_19_retencao_hidrica_inchaco.html',
    emoji: '💧',
  },
  {
    id: '20',
    slug: 'queda-cabelo-feminina',
    title: 'Queda de Cabelo Feminina',
    description: 'Causas hormonais, nutricionais e tratamentos eficazes',
    category: 'condicoes-saude',
    tags: ['alopecia', 'queda cabelo', 'saúde capilar'],
    readTime: 20,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_20_queda_cabelo_feminina.html',
    emoji: '💇',
  },
  {
    id: '21',
    slug: 'osteoporose-saude-ossea',
    title: 'Osteoporose e Saúde Óssea',
    description: 'Prevenção e tratamento da perda de densidade óssea',
    category: 'condicoes-saude',
    tags: ['osteoporose', 'saúde óssea', 'cálcio', 'vitamina D'],
    readTime: 24,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_21_osteoporose_saude_ossea.html',
    emoji: '🦴',
  },
  {
    id: '22',
    slug: 'anemia-ferropriva-mulher',
    title: 'Anemia Ferropriva na Mulher',
    description: 'Como prevenir e tratar a deficiência de ferro',
    category: 'condicoes-saude',
    tags: ['anemia', 'ferro', 'fadiga'],
    readTime: 18,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_22_anemia_ferropriva_mulher.html',
    emoji: '🩸',
  },
  {
    id: '23',
    slug: 'disturbios-alimentares-femininos',
    title: 'Distúrbios Alimentares Femininos',
    description: 'Reconhecimento, prevenção e tratamento de TAs',
    category: 'saude-mental',
    tags: ['transtornos alimentares', 'anorexia', 'bulimia', 'compulsão'],
    readTime: 28,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_23_disturbios_alimentares_femininos.html',
    emoji: '🆘',
  },
  {
    id: '24',
    slug: 'saude-cardiovascular-feminina',
    title: 'Saúde Cardiovascular Feminina',
    description: 'Prevenção de doenças cardíacas na mulher',
    category: 'condicoes-saude',
    tags: ['coração', 'cardiovascular', 'prevenção'],
    readTime: 22,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_24_saude_cardiovascular_feminina.html',
    emoji: '❤️‍🩹',
  },
  {
    id: '25',
    slug: 'enxaqueca-hormonal',
    title: 'Enxaqueca Hormonal',
    description: 'Entenda a relação entre hormônios e enxaqueca menstrual',
    category: 'condicoes-saude',
    tags: ['enxaqueca', 'cefaleia', 'hormônios'],
    readTime: 18,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_25_enxaqueca_hormonal.html',
    emoji: '🤕',
  },
  {
    id: '26',
    slug: 'candidiase-disbiose-vaginal',
    title: 'Candidíase e Disbiose Vaginal',
    description: 'Restaure o equilíbrio da microbiota íntima',
    category: 'condicoes-saude',
    tags: ['candidíase', 'disbiose', 'microbiota vaginal'],
    readTime: 20,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_26_candidiase_disbiose_vaginal.html',
    emoji: '🦠',
  },
  {
    id: '27',
    slug: 'sindrome-fadiga-cronica',
    title: 'Síndrome da Fadiga Crônica',
    description: 'Quando o cansaço extremo não passa com descanso',
    category: 'condicoes-saude',
    tags: ['fadiga crônica', 'SFC', 'energia'],
    readTime: 24,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_27_sindrome_fadiga_cronica.html',
    emoji: '😴',
  },
  {
    id: '28',
    slug: 'doencas-autoimunes-femininas',
    title: 'Doenças Autoimunes Femininas',
    description: 'Por que mulheres têm maior risco de doenças autoimunes',
    category: 'condicoes-saude',
    tags: ['autoimune', 'lúpus', 'artrite', 'tireoidite'],
    readTime: 26,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_28_doencas_autoimunes_femininas.html',
    emoji: '🛡️',
  },
  {
    id: '29',
    slug: 'amamentacao-nutricao-pos-parto',
    title: 'Amamentação e Nutrição Pós-Parto',
    description: 'Nutrição para lactação e recuperação pós-parto',
    category: 'reproducao',
    tags: ['amamentação', 'lactação', 'pós-parto'],
    readTime: 22,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_29_amamentacao_nutricao_pos_parto.html',
    emoji: '🤱',
  },
  {
    id: '30',
    slug: 'contraceptivos-impacto-metabolico',
    title: 'Contraceptivos: Impacto Metabólico',
    description: 'Como anticoncepcionais afetam metabolismo e nutrição',
    category: 'hormonios',
    tags: ['anticoncepcionais', 'pílula', 'DIU', 'metabolismo'],
    readTime: 24,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_30_contraceptivos_impacto_metabolico.html',
    emoji: '💊',
  },
  {
    id: '31',
    slug: 'puberdade-desenvolvimento-hormonal',
    title: 'Puberdade e Desenvolvimento Hormonal',
    description: 'A transição hormonal na adolescência feminina',
    category: 'hormonios',
    tags: ['puberdade', 'adolescência', 'menarca'],
    readTime: 20,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_31_puberdade_desenvolvimento_hormonal.html',
    emoji: '🌱',
  },
  {
    id: '32',
    slug: 'fertilidade-preparacao-gravidez',
    title: 'Fertilidade: Preparação para Gravidez',
    description: 'Otimize sua fertilidade com estilo de vida e nutrição',
    category: 'reproducao',
    tags: ['fertilidade', 'concepção', 'infertilidade'],
    readTime: 24,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_32_fertilidade_preparacao_gravidez.html',
    emoji: '🌟',
  },
  {
    id: '33',
    slug: 'gravidez-nutricao-gestacional',
    title: 'Gravidez: Nutrição Gestacional Completa',
    description: 'Do primeiro ao terceiro trimestre: o que comer',
    category: 'reproducao',
    tags: ['gravidez', 'gestação', 'trimestres'],
    readTime: 32,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_33_gravidez_nutricao_gestacional.html',
    emoji: '🤰',
  },
  {
    id: '34',
    slug: 'perimenopausa',
    title: 'Perimenopausa: A Transição Hormonal',
    description: 'Navegue pelos anos que antecedem a menopausa',
    category: 'hormonios',
    tags: ['perimenopausa', 'transição', 'sintomas'],
    readTime: 20,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_34_perimenopausa.html',
    emoji: '🌤️',
  },
  {
    id: '35',
    slug: 'endometriose',
    title: 'Endometriose: Guia Completo',
    description: 'Diagnóstico, tratamento e qualidade de vida com endo',
    category: 'condicoes-saude',
    tags: ['endometriose', 'dor pélvica', 'infertilidade'],
    readTime: 30,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_35_endometriose.html',
    emoji: '🌺',
  },
  {
    id: '36',
    slug: 'miomas-uterinos',
    title: 'Miomas Uterinos',
    description: 'Tudo sobre miomas: sintomas, tratamento e fertilidade',
    category: 'condicoes-saude',
    tags: ['miomas', 'útero', 'fibroma'],
    readTime: 22,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_36_miomas_uterinos.html',
    emoji: '🏥',
  },
  {
    id: '37',
    slug: 'cistos-ovarianos',
    title: 'Cistos Ovarianos',
    description: 'Tipos de cistos, diagnóstico e quando se preocupar',
    category: 'condicoes-saude',
    tags: ['cistos', 'ovários', 'ginecologia'],
    readTime: 18,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_37_cistos_ovarianos.html',
    emoji: '🔬',
  },
  {
    id: '38',
    slug: 'hiperprolactinemia',
    title: 'Hiperprolactinemia',
    description: 'Excesso de prolactina: causas e tratamento',
    category: 'hormonios',
    tags: ['prolactina', 'hiperprolactinemia', 'galactorreia'],
    readTime: 20,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_38_hiperprolactinemia.html',
    emoji: '🧪',
  },
  {
    id: '39',
    slug: 'insuficiencia-ovariana-prematura',
    title: 'Insuficiência Ovariana Prematura',
    description: 'Quando a menopausa chega antes dos 40 anos',
    category: 'hormonios',
    tags: ['IOP', 'menopausa precoce', 'falência ovariana'],
    readTime: 24,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_39_insuficiencia_ovariana_prematura.html',
    emoji: '⚠️',
  },
  {
    id: '40',
    slug: 'tdpm-transtorno-disforico',
    title: 'TDPM: Transtorno Disfórico Pré-Menstrual',
    description: 'Quando a TPM é mais grave: reconhecimento e tratamento',
    category: 'saude-mental',
    tags: ['TDPM', 'PMDD', 'sintomas graves'],
    readTime: 22,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_40_tdpm_transtorno_disforico.html',
    emoji: '😓',
  },
  {
    id: '41',
    slug: 'cortisol-estresse-feminino',
    title: 'Cortisol e Estresse na Mulher',
    description: 'Como o cortisol elevado afeta sua saúde hormonal',
    category: 'hormonios',
    tags: ['cortisol', 'estresse', 'adrenais'],
    readTime: 20,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_41_cortisol_estresse_feminino.html',
    emoji: '⚡',
  },
  {
    id: '42',
    slug: 'insulina-saude-feminina',
    title: 'Insulina e Saúde Feminina',
    description: 'O papel crucial da insulina nos hormônios femininos',
    category: 'hormonios',
    tags: ['insulina', 'glicemia', 'sensibilidade insulínica'],
    readTime: 24,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_42_insulina_saude_feminina.html',
    emoji: '📊',
  },
  {
    id: '43',
    slug: 'dominancia-estrogenica',
    title: 'Dominância Estrogênica',
    description: 'Quando o estrogênio está elevado em relação à progesterona',
    category: 'hormonios',
    tags: ['dominância estrogênica', 'excesso estrogênio', 'desequilíbrio'],
    readTime: 22,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_43_dominancia_estrogenica.html',
    emoji: '⚖️',
  },
  {
    id: '44',
    slug: 'progesterona-baixa',
    title: 'Progesterona Baixa',
    description: 'Causas, sintomas e como aumentar progesterona naturalmente',
    category: 'hormonios',
    tags: ['progesterona', 'deficiência', 'fase lútea'],
    readTime: 20,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_44_progesterona_baixa.html',
    emoji: '📉',
  },
  {
    id: '45',
    slug: 'testosterona-feminina',
    title: 'Testosterona na Mulher',
    description: 'O hormônio masculino essencial para a saúde feminina',
    category: 'hormonios',
    tags: ['testosterona', 'libido', 'massa muscular'],
    readTime: 22,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_45_testosterona_feminina.html',
    emoji: '💪',
  },
  {
    id: '46',
    slug: 'seed-cycling',
    title: 'Seed Cycling: Ciclagem de Sementes',
    description: 'Use sementes para equilibrar hormônios naturalmente',
    category: 'nutricao',
    tags: ['seed cycling', 'sementes', 'equilíbrio hormonal'],
    readTime: 16,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_46_seed_cycling.html',
    emoji: '🌻',
  },
  {
    id: '47',
    slug: 'fitoestrogenios',
    title: 'Fitoestrógenos na Alimentação',
    description: 'Estrogênios vegetais e seus efeitos na saúde',
    category: 'nutricao',
    tags: ['fitoestrógenos', 'soja', 'isoflavonas'],
    readTime: 18,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_47_fitoestrogenios.html',
    emoji: '🌿',
  },
  {
    id: '48',
    slug: 'detox-estrogenico',
    title: 'Detox Estrogênico',
    description: 'Apoie a eliminação do excesso de estrogênio',
    category: 'nutricao',
    tags: ['detox', 'metabolização estrogênio', 'fígado'],
    readTime: 20,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_48_detox_estrogenico.html',
    emoji: '🥬',
  },
  {
    id: '49',
    slug: 'anti-inflamatorios-naturais',
    title: 'Anti-inflamatórios Naturais',
    description: 'Alimentos e suplementos para reduzir inflamação',
    category: 'nutricao',
    tags: ['anti-inflamatório', 'inflamação', 'nutrição'],
    readTime: 18,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_49_anti_inflamatorios_naturais.html',
    emoji: '🔥',
  },
  {
    id: '50',
    slug: 'jejum-intermitente-hormonios',
    title: 'Jejum Intermitente e Hormônios Femininos',
    description: 'JI para mulheres: benefícios e precauções',
    category: 'nutricao',
    tags: ['jejum intermitente', 'JI', 'hormônios'],
    readTime: 24,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_50_jejum_intermitente_hormonios.html',
    emoji: '⏰',
  },
  {
    id: '51',
    slug: 'depressao-ciclo-hormonal',
    title: 'Depressão e Ciclo Hormonal',
    description: 'A relação entre hormônios e saúde mental',
    category: 'saude-mental',
    tags: ['depressão', 'saúde mental', 'hormônios'],
    readTime: 22,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_51_depressao_ciclo_hormonal.html',
    emoji: '😔',
  },
  {
    id: '52',
    slug: 'ansiedade-feminina',
    title: 'Ansiedade na Mulher',
    description: 'Por que mulheres têm mais ansiedade e como tratar',
    category: 'saude-mental',
    tags: ['ansiedade', 'saúde mental', 'estresse'],
    readTime: 20,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_52_ansiedade_feminina.html',
    emoji: '😰',
  },
  {
    id: '53',
    slug: 'libido-saude-sexual',
    title: 'Libido e Saúde Sexual Feminina',
    description: 'Desejo sexual, hormônios e bem-estar',
    category: 'hormonios',
    tags: ['libido', 'desejo', 'sexualidade'],
    readTime: 22,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_53_libido_saude_sexual.html',
    emoji: '💕',
  },
  {
    id: '54',
    slug: 'sono-hormonios-femininos',
    title: 'Sono e Hormônios Femininos',
    description: 'Como o ciclo hormonal afeta a qualidade do sono',
    category: 'ciclo-hormonal',
    tags: ['sono', 'insônia', 'melatonina'],
    readTime: 18,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_54_sono_hormonios_femininos.html',
    emoji: '😴',
  },
  {
    id: '55',
    slug: 'queda-cabelo-feminina',
    title: 'Queda de Cabelo: Causas Hormonais',
    description: 'Alopecia feminina e seus tratamentos',
    category: 'condicoes-saude',
    tags: ['alopecia', 'queda cabelo', 'DHT'],
    readTime: 22,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_55_queda_cabelo_feminina.html',
    emoji: '💇',
  },
  {
    id: '56',
    slug: 'acne-hormonal',
    title: 'Acne Hormonal',
    description: 'Entenda e trate a acne relacionada a hormônios',
    category: 'condicoes-saude',
    tags: ['acne', 'pele', 'androgênios'],
    readTime: 20,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_56_acne_hormonal.html',
    emoji: '🔴',
  },
  {
    id: '57',
    slug: 'celulite-hormonios',
    title: 'Celulite e Hormônios',
    description: 'A relação hormonal por trás da celulite',
    category: 'condicoes-saude',
    tags: ['celulite', 'estrogênio', 'gordura'],
    readTime: 18,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_57_celulite_hormonios.html',
    emoji: '✨',
  },
  {
    id: '58',
    slug: 'retencao-hidrica-ciclo',
    title: 'Retenção Hídrica no Ciclo Menstrual',
    description: 'Por que você incha antes da menstruação',
    category: 'ciclo-hormonal',
    tags: ['retenção', 'inchaço', 'edema'],
    readTime: 16,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_58_retencao_hidrica_ciclo.html',
    emoji: '💧',
  },
  {
    id: '59',
    slug: 'treinamento-ciclo-menstrual',
    title: 'Treinamento e Ciclo Menstrual',
    description: 'Adapte seu treino para cada fase hormonal',
    category: 'treinamento',
    tags: ['treino', 'periodização', 'performance'],
    readTime: 24,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_59_treinamento_ciclo_menstrual.html',
    emoji: '🏋️',
  },
  {
    id: '60',
    slug: 'reds-deficiencia-energetica',
    title: 'RED-S: Deficiência Energética Relativa no Esporte',
    description: 'Síndrome que afeta atletas femininas',
    category: 'treinamento',
    tags: ['RED-S', 'disponibilidade energética', 'atletas'],
    readTime: 26,
    htmlPath: 'D:\\ebooks\\artigos_feminino\\artigo_60_reds_deficiencia_energetica.html',
    emoji: '⚠️',
  },
];
